In [1]:
import numpy as np

In [2]:
# Generate transcation details
transction = np.random.randint(-100000, 100000, (50, 20))

In [3]:
# Seperate debit and credit transction
debit_transction = transction[np.where(transction < 0)]
debit_transction

array([-43228,  -8591, -71319, -60033, -59491,  -8419, -61564, -34714,
       -17385, -76016,  -3759, -42938, -53155, -50817, -27191, -81603,
       -29325, -52054, -88186, -59461, -50582, -41512, -88249,   -838,
       -67324,  -8456, -83018, -88892, -95916, -48731, -66269, -96737,
       -89805, -63536, -63808,  -8906, -42976, -32483, -38719,  -9947,
       -70524, -44958, -65418, -35230, -93231, -59997, -87373, -87938,
         -598, -48209, -88932, -98845,  -2290, -61445, -82838, -39237,
       -29031, -35764,  -4690, -24552, -53514, -98978, -83242, -73866,
       -39791, -90963, -99752, -37272, -17151, -58316, -51562, -95464,
       -43406, -77613, -58378, -44321, -94935, -88846,  -1737, -86138,
       -23835, -43466, -51103, -13412, -54957, -31811, -68594, -17075,
       -17237, -29289, -55887, -20345,  -7967, -66602, -91627, -74087,
       -53387, -34861, -29233, -47180, -28683, -28247, -60487, -44815,
       -86246, -54317, -96918, -13094, -44836, -31449, -66572, -66581,
      

In [4]:
# Seperate credit transction
credit_transction = transction[np.where(transction >= 0)]
credit_transction

array([61340, 56860,  2326, 51673, 27729, 21574, 62239, 34870, 18954,
       16042,  5316, 54669, 29130, 30009, 27928, 46460, 76955, 33555,
       54555, 37991, 32746, 39070, 61785, 26413, 39215, 24910, 73188,
       24445, 11415, 56490, 34552, 92312, 48930, 25864, 81736, 38963,
       12261, 47867,  3564, 75374, 94775, 76963, 19332, 82663,  2815,
       85943,  5925, 89537, 66746, 58809,  9825, 24465, 64786, 43200,
       11113, 62168, 90042, 21297, 82205, 51989, 14022, 18123, 91473,
       22403, 59319, 89722, 13506, 64991, 18203, 11767, 46804, 68534,
       14577, 45393, 57448, 48041, 13708,  9266, 49566, 61177, 30471,
       83053, 75633, 17028, 77454, 50613, 20839, 95618, 66326, 54308,
       98373, 13454, 38005, 29820, 91222, 87996, 91384, 52982, 94014,
       99623, 97954, 53134, 71863, 84217, 80111, 86818, 10357, 46779,
       69836, 56195, 89046, 91444, 92752, 42060, 59417, 81106,  1811,
       76835, 90604, 35829, 82559, 89742, 52817, 90570, 29030, 19178,
       30946, 83910,

In [5]:
# Daily net balance change
np.sum(transction, axis=0)

array([-380530,  256282,  808230, -359480, -728382,   43193,   10780,
         28718,  -51834, -122552, -751062,  564228,  808552, -203102,
       -167706,  383611, -455139,  641574, -255934,  -53194])

In [ ]:
# Identify account with continues negative balance
cum_sum = np.cumsum(transction, axis=0)
cum_sum

array([[  61340,   18112,   74972,   66381,   -4938,  -64971,  -62645,
        -122136,  -70463,  -78882, -140446, -112717,  -91143,  -28904,
         -63618,  -81003, -157019, -122149, -103195, -106954],
       [  16042,   21358,  -21580,  -74735, -125552,  -70883,  -41753,
         -68944,  -38935,  -11007,  -92610,  -46150,  -75475,    1480,
         -50574,  -17019, -105205, -164666, -215248, -256760],
       [ -88249,  -33694,    4297,   37043,   36205,  -31119,  -39575,
        -122593,  -83523,  -21738,    4675,  -84217,  -45002,  -20092,
          53096,  -42820,  -91551,  -67106,  -55691, -121960],
       [ -96737,  -40247, -130052, -193588, -257396, -266302, -231750,
        -274726, -182414, -133484, -165967, -140103,  -58367,  -19404,
          -7143,   40724,    2005,   -7942,   -4378,  -74902],
       [  75374,  170149,  125191,   59773,  136736,  101506,    8275,
         -51722,  -32390,   50273,  -37100, -125038, -122223, -122821,
        -171030,  -85087,  -79162, -16

In [7]:
# Modify array to test
cum_sum[1] = [-1, -23, -367, -345, -46, -84, -65, -66, -97, -98, -1, -23, -367, -345, -46, -84, -65, -66, -97, -98]

# Accounts having continuous negative balance
negative_balance = np.all(cum_sum < 0, axis=1)
np.where(negative_balance)[0]

array([ 1,  7, 23, 39, 49])